kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: gradle:jdk17-alpine
  commands:
  - ./gradlew build
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: publish
    files: build/libs/sotify*.jar
