name: ${name}
version: ${version}
description: ${description}
author: ${author}
main: ${main}
api-version: ${api}
commands:
  sotify:
    description: Reload configuration
    usage: "/sotify"

permissions:
  sotify:
    default: op
    description: Allows to reload plugin configuration